#!/usr/bin/env escript
%%! -pa ebin

%% Runs a game of mastermind.  The program makes a random code, then
%% breaks it in as few guesses as it can manage.

%% These two lines are optional.
%%
-module(main).
-export([main/1]).
-mode(native).

main([]) ->
    gameplayer:go();
main(_) ->
    io:format("Usage: mastermind [Number of games]~n").
